// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnCB6_jCxUiqhNh6yxdT9aZ_AExlCpM0g',
    appId: '1:692811497257:web:53e271168b725aaff88138',
    messagingSenderId: '692811497257',
    projectId: 'moaapp-5a164',
    authDomain: 'moaapp-5a164.firebaseapp.com',
    databaseURL: 'https://moaapp-5a164-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'moaapp-5a164.appspot.com',
    measurementId: 'G-5V4FGWF42P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAsf4XPxREw_ReI1-q1CYVT0X817UH5hc',
    appId: '1:692811497257:android:0f7a2fc98a118d67f88138',
    messagingSenderId: '692811497257',
    projectId: 'moaapp-5a164',
    databaseURL: 'https://moaapp-5a164-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'moaapp-5a164.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9GKB1VHED9HfZH_EfmwQrxcMSENNAyAE',
    appId: '1:692811497257:ios:33b8cd379c5c0cedf88138',
    messagingSenderId: '692811497257',
    projectId: 'moaapp-5a164',
    databaseURL: 'https://moaapp-5a164-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'moaapp-5a164.appspot.com',
    iosBundleId: 'com.example.moaTodo',
  );
}
